### ISSUE TITLE
Link to SAMRi10-Tool does not work anymore

### ISSUE THREAD

**Issue by StephanGa** [MicrosoftDocs/ATADocs.de-de#27]
The link to the SAMRi10 Tool does not work anymore.
Maybe it is possible to scan all MS sites for referrals to the gallery technet site.

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 0300af32-7568-5553-e183-e15e490456a3
* Version Independent ID: 47bfec66-9a46-c09e-f8f7-f4b49aed56bb
* Content: [Handbuch zu verdächtigen ATA-Aktivitäten](https://docs.microsoft.com/de-de/advanced-threat-analytics/suspicious-activity-guide#reconnaissance-using-directory-services-queries)
* Content Source: [ATADocs/suspicious-activity-guide.md](https://github.com/MicrosoftDocs/ATADocs.de-de/blob/live/ATADocs/suspicious-activity-guide.md)
* Product: **advanced-threat-analytics**
* Technology: ****
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by dcurwin** [comment]
#assign:dcurwin

**Comment by dcurwin** [comment]
@StephanGa  - Thanks for your comment. We will investigate the issue and get back to you.

**Comment by dcurwin** [comment]
We've removed the outdated link. Thanks for your comment.

**Comment by dcurwin** [comment]
#please-close

**Comment by SonjaSaltzman** [comment]
Closing the issue as it is resolved (invalid link removed), cc @JasonCard
